######################################
# UX Test Config for metaflow-temporal
######################################

scheduler:
  scheduler_type: temporal
  deploy_args:
    temporal_host: "localhost:7233"

compute_env:
  METAFLOW_DEFAULT_METADATA: local
  METAFLOW_DEFAULT_DATASTORE: local
  METAFLOW_DEFAULT_ENVIRONMENT: local
